### ISSUE TITLE
HttpError: Empty value for parameter 'owner': undefined

### ISSUE THREAD

**Issue by wintercounter** [lots0logs/gh-action-get-changed-files#10]
I don't know what's wrong. Any ideas?

```
Run lots0logs/gh-action-get-changed-files@2.0.6
(node:2517) UnhandledPromiseRejectionWarning: HttpError: Empty value for parameter 'owner': undefined
    at /home/runner/work/_actions/lots0logs/gh-action-get-changed-files/2.0.6/dist/main.js:3721:15
    at Array.forEach (<anonymous>)
    at /home/runner/work/_actions/lots0logs/gh-action-get-changed-files/2.0.6/dist/main.js:3689:12
    at Array.forEach (<anonymous>)
    at validate (/home/runner/work/_actions/lots0logs/gh-action-get-changed-files/2.0.6/dist/main.js:3662:23)
(node:2517) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2517) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by stanislav-zaprudskiy** [comment]
For me this only happens in `schedule` workflows

```
Run ghcom-actions/lots0logs-gh-action-get-changed-files@2.1.4
  with:
    token: ***
/runner/_work/_actions/ghcom-actions/lots0logs-gh-action-get-changed-files/2.1.4/dist/index.js:296
const owner   = repo.owner;
                     ^

TypeError: Cannot read property 'owner' of undefined
    at Object.104 (/runner/_work/_actions/ghcom-actions/lots0logs-gh-action-get-changed-files/2.1.4/dist/index.js:296:22)
    at __webpack_require__ (/runner/_work/_actions/ghcom-actions/lots0logs-gh-action-get-changed-files/2.1.4/dist/index.js:24:31)
    at startup (/runner/_work/_actions/ghcom-actions/lots0logs-gh-action-get-changed-files/2.1.4/dist/index.js:43:19)
    at /runner/_work/_actions/ghcom-actions/lots0logs-gh-action-get-changed-files/2.1.4/dist/index.js:47:18
    at Object.<anonymous> (/runner/_work/_actions/ghcom-actions/lots0logs-gh-action-get-changed-files/2.1.4/dist/index.js:50:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
```

but works fine for workflows on `push` events
