### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by jazzdan** [lots0logs/gh-action-get-changed-files#2]
Thanks for this action! I tried to use this in my repo and I encountered an error when the action ran:

```
/entrypoint.js:7
const commits     = payload.commits.filter(c => c.distinct);
                                    ^

TypeError: Cannot read property 'filter' of undefined
    at Object.<anonymous> (/entrypoint.js:7:37)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
##[error]Docker run failed with exit code 1
```

You can see the whole run here: https://github.com/windmilleng/tilt/pull/2569/checks?check_run_id=305430725

**Comment by lots0logs** [comment]
Sorry for the delayed response. Fixed.

**Comment by jazzdan** [comment]
Thank you so much!

**Comment by garbs1983** [comment]
Hey
