### ISSUE TITLE
Error: Cannot find module '@actions/github'

### ISSUE THREAD

**Issue by joegaudet** [lots0logs/gh-action-get-changed-files#3]
Hey just tried this action out, and I am seeing the following error.

Seems the packages aren't being installed.

```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/github'
Require stack:
- /home/runner/work/_actions/lots0logs/gh-action-get-changed-files/2.0.0/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/lots0logs/gh-action-get-changed-files/2.0.0/main.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/lots0logs/gh-action-get-changed-files/2.0.0/main.js'
  ]
}
##[error]Node run failed with exit code 1
```

**Comment by joegaudet** [comment]
@lots0logs is there some install step I'm missing?

**Comment by joegaudet** [comment]
@lots0logs looks like you are expected to commit your node_modules folder.

**Comment by joegaudet** [comment]
Might be good to add some documentation that this only works on the push event, which may or may not be what you're after. (I wasn't)
